version: '3.7'

services:
  utility:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
    env_file:
      - .env
      - .env.local
    image: ubuntu:18.04
    restart: always
    container_name: eeca-meetup-jan-2023-utility
    volumes:
      - .:/var/www
      - cache-volume:/cache-volume
      - uploads-volume:/uploads-volume
    command: bash -c "chmod +x /var/www/docker/utility/prod.sh && /var/www/docker/utility/prod.sh"

  app:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first
      labels:
        ## Traefik config ##
        - traefik.enable=true
        - traefik.docker.network=traefik
        - traefik.http.services.eeca_meetup_jan_2023_prod.loadbalancer.server.port=80

        - traefik.http.routers.eeca_meetup_jan_2023_prod.entrypoints=web
        - traefik.http.routers.eeca_meetup_jan_2023_prod.rule=Host(`eeca-meetup-jan-2023.buzzingpixel.com`)
    volumes:
      - cache-volume:/var/www/system/user/cache
      - uploads-volume:/var/www/public/uploads
    networks:
      - traefik
      - default

  db:
    deploy:
      rollback_config:
        order: start-first
      update_config:
        order: start-first

networks:
  traefik:
    name: traefik
    external: true

volumes:
  cache-volume:
  uploads-volume:

